In [1]:
import numpy as np

In [2]:
one = np.arange(8)

In [3]:
one

array([0, 1, 2, 3, 4, 5, 6, 7])

In [7]:
one[5]

5

In [9]:
one[5:7]

array([5, 6])

In [10]:
one[:6]

array([0, 1, 2, 3, 4, 5])

In [11]:
one[:4] = 100

In [12]:
one

array([100, 100, 100, 100,   4,   5,   6,   7])

In [13]:
lisy = [2, 5, 6, 7, 8, 9, 4, 45, 67]

In [14]:
lisy[:5] = 100

TypeError: can only assign an iterable

In [16]:
one = np.arange(0, 11)

In [17]:
one

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
slice_of_array = one[:7]

In [19]:
slice_of_array

array([0, 1, 2, 3, 4, 5, 6])

In [20]:
slice_of_array[:] = 99

In [21]:
slice_of_array

array([99, 99, 99, 99, 99, 99, 99])

In [22]:
one

array([99, 99, 99, 99, 99, 99, 99,  7,  8,  9, 10])

In [23]:
copy = one.copy()

In [24]:
copy

array([99, 99, 99, 99, 99, 99, 99,  7,  8,  9, 10])

In [28]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [29]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [33]:
arr_2d[2,1]

40

In [34]:
arr_2d[1]

array([20, 25, 30])

In [35]:
arr_2d[1:,1:]

array([[25, 30],
       [40, 45]])

In [36]:
arr_2d[:, 0:2 ]

array([[ 5, 10],
       [20, 25],
       [35, 40]])

In [42]:
arr_2d[1:]

array([[20, 25, 30],
       [35, 40, 45]])

In [52]:
 bol = arr_2d < 26

In [53]:
arr_2d[bol]

array([ 5, 10, 15, 20, 25])

In [54]:
arr_2d[arr_2d == 40]

array([40])

In [55]:
third = np.arange(0, 50).reshape(5, 10)

In [56]:
third

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [58]:
third[1:3, 3:5]

array([[13, 14],
       [23, 24]])

In [59]:
third[:, 7: 9]

array([[ 7,  8],
       [17, 18],
       [27, 28],
       [37, 38],
       [47, 48]])

In [60]:
third + third

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [61]:
arri = np.arange(0, 11)

In [62]:
arri

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
arri + arri

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [64]:
arri * 8

array([ 0,  8, 16, 24, 32, 40, 48, 56, 64, 72, 80])

In [65]:
arri + 67

array([67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77])

In [66]:
arri / arri

C:\Users\Pc\AppData\Local\Temp\ipykernel_9544\991487782.py:1: RuntimeWarning: invalid value encountered in true_divide
  arri / arri


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [67]:
1 / arri

C:\Users\Pc\AppData\Local\Temp\ipykernel_9544\2206757676.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / arri


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [68]:
np.sqrt(arri)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [70]:
np.exp(arri)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [71]:
np.log(arri)

C:\Users\Pc\AppData\Local\Temp\ipykernel_9544\1625391883.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arri)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [72]:
np.max(arri)

10