In [1]:
my_list = [1, 2, 3]

In [3]:
my_list

[1, 2, 3]

In [4]:
import numpy as np

In [6]:
arr = np.array(my_list)

In [7]:
arr

array([1, 2, 3])

In [8]:
my_list2 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(my_list2)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.ones((6,1))

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [19]:
np.linspace( 1, 60, 10)

array([ 1.        ,  7.55555556, 14.11111111, 20.66666667, 27.22222222,
       33.77777778, 40.33333333, 46.88888889, 53.44444444, 60.        ])

In [20]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [80]:
np.random.rand(4, 4)

array([[0.12381216, 0.83320143, 0.52248586, 0.5643521 ],
       [0.42767675, 0.80847413, 0.170194  , 0.71445255],
       [0.9292166 , 0.14263933, 0.22013087, 0.17807878],
       [0.59203999, 0.46327336, 0.52326304, 0.31030481]])

In [24]:
np.random.randn(5)

array([-0.03888372, -0.15803122, -0.76673602,  0.75201153, -0.0222558 ])

In [32]:
np.random.randint(5,12, 8)

array([ 6,  9,  5,  7,  6,  6,  6, 10])

In [34]:
variable = np.arange(25)

In [35]:
variable

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [58]:
variable2 = np.random.randint(0,50,12)

In [59]:
variable2

array([13,  2,  8, 13, 47, 46, 27,  1, 18, 25, 14, 43])

In [60]:
variable.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [77]:
variable.shape

(25,)

In [61]:
variable2.max()

47

In [62]:
variable2.min()

1

In [63]:
variable2

array([13,  2,  8, 13, 47, 46, 27,  1, 18, 25, 14, 43])

In [64]:
variable2.argmax()

4

In [65]:
variable2.argmin()

7

In [66]:
variable2.shape

(12,)

In [75]:
variable3 = variable2.reshape(6,2)

In [76]:
variable3

array([[13,  2],
       [ 8, 13],
       [47, 46],
       [27,  1],
       [18, 25],
       [14, 43]])

In [74]:
variable3.shape

(6, 2)

In [78]:
variable3.dtype

dtype('int32')

In [98]:
from numpy.random import rand

In [102]:
rand(4, 4)

array([[0.46353224, 0.32095953, 0.27564293, 0.77920776],
       [0.13260804, 0.88259529, 0.08251684, 0.83053936],
       [0.21928259, 0.86491223, 0.16041364, 0.16694214],
       [0.84620414, 0.10138763, 0.350337  , 0.36985986]])